spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration
    - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
    - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:org/sft/sample/web/*/mapper/*.xml
  type-aliases-package: org.sft.sample.web
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    default-fetch-size: 10
    lazy-loading-enabled: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  
  
  